project:
  type: website
  output-dir: docs

website:
  title: "431 Project A"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: proposal.qmd
        text: Proposal
      - href: analyses.qmd
        text: Analyses
      - href: portfolio.qmd
        text: Portfolio
      - href: examples.qmd
        text: Examples
      - text: "Movies"
        menu: 
        - text: "Analysis 1"
          href: 431-movies-analysis1.qmd
        - text: "Analysis 2"
          href: 431-movies-analysis2.qmd
        - text: "Analysis 3"
          href: 431-movies-analysis3.qmd
      
    right:
      - href: https://thomaselove.github.io/431-2023/contact.html
        text: "Contact Us"
      - href: https://thomaselove.github.io/431-2023
        text: "431 Homepage"

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    number-sections: true
    date-format: iso
    link-external-icon: true
    link-external-newwindow: true

editor: source
