---
title: "Project A Analyses"
author: "431 Staff"
date: last-modified
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# We will post full instructions before our first class. For now, ignore this draft.

Using the tibble you've developed following the instructions on the [Data](data.qmd) and [Proposal](proposal.qmd) pages, you will then create the remainder of your report by performing the analytic tasks specified below.

Each of these tasks should include R code that creates the information you need, **and** complete English sentences that interpret those results. Again, you have to be able to reason about what you've done, not just generate the code to solve the problem.

# Analysis 1: Simple Linear Regression Model

Provide evidence regarding the question of how well your Analysis 1 outcome can be predicted using your Analysis 1 predictor. This should include a report on the effectiveness of a simple linear regression model, and an appropriate plot of the relationship. Important steps to include in your analytic report include:

In your portfolio (section 12.1), you built (and will now edit) your careful statement of the **research question** you are trying to answer with this analysis. At the end of this Analysis, a clear and appropriate **response** to that research question is required, accompanied by a clear description of the limitations of your work. 

- Most of the time, one model won't let you come to a strong conclusion about a question of interest, and it is your job to accurately present what information can be specified as a result of the model, without overstating your conclusions. 
- This (the specification of your research question and your response) is the most important part of Analysis 1.

You will need to build a visualization of the relationship between the outcome (Y-axis) and the predictor (X-axis) and a written description of what you learn about the association (which should include comments about its direction, shape and strength along with identification of any substantial outliers). You'll also provide:

- A specification of any transformations you choose to apply to the X or Y variable in order to obtain a better fit with a simple linear regression, along with some justification for the choice (or for the decision not to apply a transformation.)
- A specification of the actual prediction equation created by your linear model, and an interpretation of what the coefficients mean, and how they should be interpreted in light of their estimated standard errors.
- A loess smooth and a linear model fit line as part of your plot.
- A specification of summary measures of goodness of fit, at a minimum the residual standard deviation (sigma) and the r-squared value. The quality of fit is not a consideration in the grading of this work.
- Identification of the two counties (by name and state) where the model is least successful at predicting the outcome.

The rest of the material below forms an outline of Analysis 1.

## The Variables

In this section you will build a simple linear regression model to predict your outcome using one of your two quantitative predictors (it's your choice.) Start by identifying those variables, and restricting your data set for this analysis to the complete cases on those variables.

- Use complete English sentences to identify your outcome and your predictor, describing what each variable means and its units of measurement.
- Also specify the name of each variable in your tibble (making it clear which is the outcome and which the predictor), the name of your tibble, which states you're studying, and how many counties have complete data on both variables.
- Finally, specify the values of your outcome and predictor for Cuyahoga County, in Ohio, where CWRU's campus is located.

## Research Question

Here, you should restate your research question clearly, following the path set out in your proposal, tweaked as necessary in light of the work you've now completed. Remember that a research question will end with a question mark, and will be something you will be able to answer (or at least respond to effectively) after your analysis is complete.

## Visualizing the Data

Provide an attractive, well-labeled scatterplot of your outcome and predictor, before any transformations, including all code necessary to build it, and describe what the plot tells you about the association of the variables, as detailed in the instructions.

## Transformation Assessment

Here, you will provide information about any transformations you chose to apply to the outcome, and explain why you did (or didn't) choose to use a transformation. 

- If you decide to use a transformation, specify the transformation you've chosen carefully, and show the scatterplot of the transformed data, using the same suggestions as were provided in the previous section to describe the resulting plot. Write a few sentences describing the transformations you considered, and why you thought this was the most promising, and why you eventually decided to use the transformed versions of your variables.

- If you decide **not** to use a transformation, identify the ONE plot which was the most promising of available transformations and show that one. Write a few sentences describing the transformations you considered, and why you thought this was the most promising, and why you eventually decided to stick with the original versions of the variables.

### Tips on the Transformation Assessment

Your response will include ONE plot demonstrating a particular transformation, although you will probably fit and view several plots in order to select a final one for this work. 

For this part of Project A, confine your search to either a logarithm, an inverse, or a square as applied to the outcome. If you want to consider one of those transformations for the predictor as well, that's OK but not crucial. You should select the most promising transformation on the basis of a scatterplot (perhaps with a loess smooth and linear fit) after the transformation has been applied. 

You are discouraged from using numerical summaries of fit in this section. Of course, summary statistics like $R^2$ when the outcome is transformed will definitely not be comparable.

## The Fitted Model

Fit your model to use your predictor to predict your outcome (applying your selected transformation) and provide the code you used, and the following summary elements in this section.

1. A written statement of the full prediction equation, with coefficients nicely rounded, and a careful description of what the coefficients mean in context. 

2. A tidy summary of the model's coefficients, including 90% confidence interval for model estimates.

3. The model's R-squared, residual standard error, the number of observations to which the model was fit, and the Pearson correlation of your predictor and outcome.

## Residual Analysis

Here, you'll need to do four things.

1. prepare a pair of residual plots (one to assess residuals vs. fitted values for non-linearity, and one to assess Normality in the residuals or the standardized residuals.) 
2. interpret those plots in terms of what they tell you about how well the assumptions of linearity and Normality hold for your setting, in complete English sentences.
3. display your model's prediction for the original (untransformed) outcome you are studying for Cuyahoga County, in Ohio, and compare it to Cuyahoga's actual value of this outcome.
4. identify the two counties (by name and state) where the model you've fit is least successful at predicting the outcome (in the sense of having the largest residual in absolute value.)

- The `augment` function would be very helpful here.
- If you model is called `m1`, you could use something like `plot(m1, which = c(1:2))` to obtain these two plots and that's OK.
- You can produce a more pleasing picture using `ggplot2` and `patchwork` following the strategy I've demonstrated multiple times in the slides and the Course Notes, should you desire.

## Conclusions and Limitations

Here, you'll write two paragraphs.

In the first paragraph, you should provide a clear restatement of your research question, followed by a clear and appropriate response to your research question, motivated by your results.

Then, write a paragraph which summarizes the key limitations of your work in Analysis 1. 
- If you see problems with regression assumptions in your residual plot, that would be a good thing to talk about here, for instance. 
- Another issue that is worth discussing is your target population, and what evidence you can describe that might indicate whether your selected states are a representative sample of the US as a whole, or perhaps some particular part of the United States.

# Analysis 2: Comparing Two Independent Samples

Here, you have identified one quantitative (Analysis 2 outcome) and one categorical variable (Analysis 2 binary predictor.) 

You’ll analyze the results and build a 90% confidence interval for the difference in means with an appropriate t-based or bootstrap procedure. 

You will provide complete code, appropriate visualizations and detailed explanations of your analytic decisions, and conclusions.

We are looking for:

- Descriptive and exploratory summaries of the data across the two predictor groups for your chosen outcome, including, of course, attractive and well-constructed visualizations.
- Comparisons of the population mean difference for your Analysis 2 outcome across a set of two groups defined by your Analysis 2 predictor, including appropriate demonstrations of the reasons behind the choices you made between parametric and bootstrap procedures.

## Analysis 2 Specifications

- Your Analysis 2 material should start with specifications of what each of the variables you are studying in this analysis actually mean, and how your sample was taken from the CHR 2023 data.
- Your cleaning, creation of your groups and other data management activities should already have been shown in earlier sections. Please refer back to those and don’t repeat what you’ve already done. Be sure that the Codebook you provided describes both of the variables you are using in your analyses here.
- Provide numerical summaries and visualizations of interest that are relevant to this analysis, and comment on any issues you observe.
- For your main analysis, show your work and your reasoning (not just your code), and comment on any analytic decisions you make. 
- Be sure to actively present and justify any assumptions you are making.
- Finally, answer your research question, by clearly linking the analytic results to what you were asking at the start.
- If you can see a logical next step for the analysis of the question you asked, specify it. Also, if you specified a pre-existing belief about what would happen, reflect on that in light of the data.

# Analysis 3: Comparing An Outcome in 2023 to its value in 2018

Here, we have identified two quantitative variable (the same outcome in two different time periods) which are paired (so that they have a natural link between them, and use the same units of measurement.) 

You’ll analyze the results and build a 90% confidence interval for the population mean difference with an appropriate t-based or bootstrap procedure. 

Again, you will provide complete code, appropriate visualizations and detailed explanations of your analytic decisions, and conclusions.

## Analysis 3 Specifications

- Your Analysis 3 material should start with specifications of what the outcome you are studying in this analysis actually means, and how your samples in 2018 and 2023 were created.
- Your cleaning, creation of your groups and other data management activities should already have been shown in earlier sections. Please refer back to those and don’t repeat what you’ve already done. Be sure that the Codebook you provided describes both of the variables you are using in your analyses here.
- Provide numerical summaries and visualizations of interest that are relevant to this analysis, and comment on any issues you observe.
- For your main analysis, show your work and your reasoning (not just your code), and comment on any analytic decisions you make. 
- Be sure to actively present and justify any assumptions you are making.
- Finally, answer your research question, by clearly linking the analytic results to what you were asking at the start.
- If you can see a logical next step for the analysis of the question you asked, specify it. Also, if you specified a pre-existing belief about what would happen, reflect on that in light of the data.
