---
title: "Examples"
author: "431 Staff"
date: last-modified
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# Project A Proposal Materials

1. The **sample proposal** using 2019 data is available now. The Quarto file is called `431-projA-sample-portfolio.qmd` and it is part of the regular downloads of data and code at our [431-data site](https://github.com/THOMASELOVE/431-data). I would start by looking at the [HTML result we've posted to RPubs](https://rpubs.com/TELOVE/projectA-sample-proposal).

2. The **proposal template**, which we used to build the sample proposal, is also available as part of [the 431-data site](https://github.com/THOMASELOVE/431-data). It is called `431-projA-portfolio-template.qmd`. The [HTML version is also at RPubs](https://rpubs.com/TELOVE/projectA-proposal-template).

# Project A Portfolio Report Materials

3. The **portfolio report template**, which we used to build the sample portfolio report, is also available as part of [the 431-data site](https://github.com/THOMASELOVE/431-data). It is called `431-projA-report-template.qmd`. The [HTML version is also at RPubs](https://rpubs.com/TELOVE/projectA-report-template).

4. The **sample portfolio report** adds only a little to what you had in the sample proposal (since I chose not to work through the Analyses for you), but it is available as part of [the 431-data site](https://github.com/THOMASELOVE/431-data). It is called `431-projA-sample-report.qmd`. The [HTML version is also at RPubs](https://rpubs.com/TELOVE/projectA-sample-report).

# Sample Analyses using the Favorite Movies Data

5. [Favorite Movies: Analysis 1](431-movies-analysis1.qmd) (Simple Regression), with Quarto code available at [our 431-data site](https://raw.githubusercontent.com/THOMASELOVE/431-data/main/data-and-code/431-movies-analysis1.qmd).

6. [Favorite Movies: Analysis 2](431-movies-analysis2.qmd) (Independent Samples), with Quarto code available at [our 431-data site](https://raw.githubusercontent.com/THOMASELOVE/431-data/main/data-and-code/431-movies-analysis2.qmd).

7. [Favorite Movies: Analysis 3](431-movies-analysis3.qmd) (Paired Samples), with Quarto code available at [our 431-data site](https://raw.githubusercontent.com/THOMASELOVE/431-data/main/data-and-code/431-movies-analysis3.qmd).