---
title: "Project A Portfolio"
author: "431 Staff"
date: last-modified
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# Please ignore these instructions until the first class meeting, while we continue to build them.

## Your Final Submission involves Three Parts

1. **The Report** You will submit a polished report in both R Markdown and HTML augmenting the work you developed in the Proposal addressing all of the issues described in the Proposal and now adding in the Analytic Tasks and Conclusions material. You should also submit your main data file (`chr_2022_YOURNAME.Rds`).

**NEW** Dr. Love has provided a [Full Project A Sample](exampleC.qmd), actually four of them (each using a different theme, but otherwise identical) which includes some revised proposal materials, followed by the outline for the analyses. A list of all of the changes from the "proposal" example to this "full project" example [is provided here](https://github.com/THOMASELOVE/431-classes-2022/blob/main/projectA/changes_from_proposal.md). The bottom line is that, ideally, everyone will now have **the same 9 Sections** in this revised Sample Project in their Final Project A, as indicated in the [Full Project A Sample](exampleC.qmd).

1. Preliminaries
2. Data Development
3. Our Analytic Tibble
4. Codebook
5. Biggest Challenge
6. Analysis 1
7. Analysis 2
8. Analysis 3
9. Session Information

Note that there is a [checklist for the final report](check_final.qmd) as part of the [Examples & Tips](check_final.qmd) page that includes many things we'll be looking for in grading. It's well worth your time to review the checklist before submitting your work.

2. **The Video** You will produce a video in mp4 format of no more than 3 minutes in length if you're working alone, and of no more than 5 minutes in length between you if you are working in a pair. In this video, you will describe what you believe to be the most important findings for your choice of two of the three analytic tasks you have completed, while explaining your process of cleaning and managing the data as much as you believe is necessary for people to understand and evaluate your conclusions.
    - If you are working alone on the project, begin your presentation by introducing yourself and describing your sample (which states you used and specifying the research questions you'll be addressing in your discussion.)
    - If you are working in a pair, each of you will present one of the two analyses, either in two separate videos (which combined are no more than 5 minutes long) or in one video. In either case, introduce yourself at the start of your portion of the video, and specify the states you used (even though you and your partner will be using the same states) and the research question you'll be addressing.
    - Your video must include your face (so recording in Zoom is preferable) and must share graphs and results taken from the report you build.
    - All videos should include a clear statement of the research questions for any analyses presented, and justify the responses to those questions with results from the analyses.
    - The video must stand on its own, in the sense that it must be completely understandable to someone who has not read your report, but who is generally familiar with County Health Rankings and its measurements. You need to tell us everything we need to know to evaluate your claims, and no more.

3. **The Self-Evaluation** Once you have submitted the other two elements of your project, you will each (whether working alone or with a partner) submit [a brief self-evaluation via this Google Form](https://bit.ly/431-projectA-self-evaluation-2022). The form should take about 10 minutes to complete.
    - If you're curious, the form asks you to address multiple issues related to the Project in multiple-choice questions. There are also two little essays that we'll ask for, which should be written independently from your partner (if you have one).
        - You will summarize the key finding of your Project A study in your own well-chosen words (where your response should be in the neighborhood of 75 words, describing one key finding, which might come from any of your three analyses.) 
        - Also, you will tell us what the most important piece of advice is that you wished you'd heard when you began Project A (and we'd like at least 25 words here).

All three elements are due at the end of October, specifically at the time and date indicated on the [Course Calendar](https://thomaselove.github.io/431-2022/calendar.html). 

### Grading

- Project A is graded on a scale from 0 to 100, theoretically, although I expect the highest grade to be close to 95. Dr. Love works with the TAs to provide feedback and grade the projects, but the final Project A grade is determined solely by him.
- A successful Proposal is a mandatory part of Project A, and is worth 25 points as part of the Project A grade. 
- The Report is worth 35 points. It is unlikely that anyone will score above 33 points, which is the planned score for a completely accurate and polished report. Most scores will likely fall between 23 and 32 points on this element.
    - The most important parts of the Report are accurate (and effectively presented) data development, accurate (and effectively presented) analyses, and the appropriateness of your research questions and your responses to them in light of your analyses.
    - Most of the feedback you will receive on your Project A report will relate to specific grading criteria and a rubric that will be evaluated (mostly) by the teaching assistants. The checklist we used to help build the rubric is available to you as part of the [Examples & Hints](check_final.qmd) page.
- The Video is worth 30 points. It is unlikely that anyone will score above 28 points, which is the planned score for a very strong presentation, which is clear to see and hear and which is effective. Most scores will likely fall between 20 and 27 points on this element.
    - All videos should include a clear statement of the research questions for any analyses presented, and justify the responses to those questions with results from the analyses.
    - Most of the comments Professor Love builds in response to your Project A will relate to the Video. Do not treat it lightly. It is a vital part of the work, despite its short length.
- The Self-Evaluation is worth 10 points. People who complete each question on the self-evaluation thoughtfully and on time will receive the full 10 points.

Overall, a project score of 89 or higher is regarded as an A, and a score of 70 to 84 is regarded as a B, with scores between 85 and 88 falling somewhere in between. Project grading is set up to generate a median score near 85.

### Hint: More isn't better.

To improve your grade, perform the elements of the data science cycle (ingestion, tidying, transforming, visualizing, modeling and communicating) more effectively. Presenting work that isn't relevant to addressing the issues in question will not help your grade. Also, rehearse your video and make sure you present clearly and understandably throughout the (admittedly short) presentation. Make clear choices about what to include - that's key. Do not just show us everything you did.

A stronger grade will be associated with doing the tasks we've discussed more effectively. Adding a lot of additional and unnecessary analyses/work without editing down to the important issues will not improve your grade, but rather have the opposite effect. We want to see polished, accurate, clear work. Making things clearer is the hardest thing to do, and so it's the thing that impresses us most. 

