<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="431 Staff">
<meta name="dcterms.date" content="2023-08-17">

<title>431 Project A - Project A Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">431 Project A</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./data.html" rel="" target="" aria-current="page">
 <span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html" rel="" target="">
 <span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./analyses.html" rel="" target="">
 <span class="menu-text">Analyses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./portfolio.html" rel="" target="">
 <span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./examples.html" rel="" target="">
 <span class="menu-text">Examples</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://thomaselove.github.io/431-2023/contact.html" rel="" target="">
 <span class="menu-text">Contact Us</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://thomaselove.github.io/431-2023" rel="" target="">
 <span class="menu-text">431 Homepage</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#we-will-post-full-instructions-before-our-first-class.-for-now-ignore-this-draft." id="toc-we-will-post-full-instructions-before-our-first-class.-for-now-ignore-this-draft." class="nav-link active" data-scroll-target="#we-will-post-full-instructions-before-our-first-class.-for-now-ignore-this-draft.">We will post full instructions before our first class. For now, ignore this draft.</a></li>
  <li><a href="#what-data-will-i-use" id="toc-what-data-will-i-use" class="nav-link" data-scroll-target="#what-data-will-i-use">What Data Will I Use?</a></li>
  <li><a href="#developing-the-data-five-data-tasks" id="toc-developing-the-data-five-data-tasks" class="nav-link" data-scroll-target="#developing-the-data-five-data-tasks">Developing the Data: Five Data Tasks</a></li>
  <li><a href="#data-task-1.-ingest-the-raw-data-into-chr_2023_raw-then-filter-to-ranked-counties" id="toc-data-task-1.-ingest-the-raw-data-into-chr_2023_raw-then-filter-to-ranked-counties" class="nav-link" data-scroll-target="#data-task-1.-ingest-the-raw-data-into-chr_2023_raw-then-filter-to-ranked-counties">Data Task 1. Ingest the raw data into <code>chr_2023_raw</code>, then filter to ranked counties</a></li>
  <li><a href="#data-task-2.-filter-your-data-to-the-300-800-counties-in-six-states-including-ohio" id="toc-data-task-2.-filter-your-data-to-the-300-800-counties-in-six-states-including-ohio" class="nav-link" data-scroll-target="#data-task-2.-filter-your-data-to-the-300-800-counties-in-six-states-including-ohio">Data Task 2. Filter your data to the 300-800 counties in six states (including Ohio)</a>
  <ul class="collapse">
  <li><a href="#states-you-can-select" id="toc-states-you-can-select" class="nav-link" data-scroll-target="#states-you-can-select">States You Can Select</a></li>
  </ul></li>
  <li><a href="#data-task-3.-add-five-selected-measures-to-four-required-variables-and-clean-up-chr_2023" id="toc-data-task-3.-add-five-selected-measures-to-four-required-variables-and-clean-up-chr_2023" class="nav-link" data-scroll-target="#data-task-3.-add-five-selected-measures-to-four-required-variables-and-clean-up-chr_2023">Data Task 3. Add five selected measures to four required variables and clean up <code>chr_2023</code></a>
  <ul class="collapse">
  <li><a href="#select-five-of-these-45-variables" id="toc-select-five-of-these-45-variables" class="nav-link" data-scroll-target="#select-five-of-these-45-variables">Select five of these 45 variables</a></li>
  <li><a href="#what-will-these-variables-become" id="toc-what-will-these-variables-become" class="nav-link" data-scroll-target="#what-will-these-variables-become">What will these variables become?</a></li>
  <li><a href="#information-to-help-select-and-build-a-codebook" id="toc-information-to-help-select-and-build-a-codebook" class="nav-link" data-scroll-target="#information-to-help-select-and-build-a-codebook">Information to help select and build a codebook</a></li>
  <li><a href="#how-to-clean-your-selected-variables" id="toc-how-to-clean-your-selected-variables" class="nav-link" data-scroll-target="#how-to-clean-your-selected-variables">How To Clean Your Selected Variables</a>
  <ul class="collapse">
  <li><a href="#ratios-that-need-converting" id="toc-ratios-that-need-converting" class="nav-link" data-scroll-target="#ratios-that-need-converting">Ratios That Need Converting</a></li>
  <li><a href="#variables-that-should-be-rescaled" id="toc-variables-that-should-be-rescaled" class="nav-link" data-scroll-target="#variables-that-should-be-rescaled">Variables that should be rescaled</a></li>
  <li><a href="#variables-that-are-proportions-should-be-converted-to-percentages" id="toc-variables-that-are-proportions-should-be-converted-to-percentages" class="nav-link" data-scroll-target="#variables-that-are-proportions-should-be-converted-to-percentages">Variables that are Proportions should be converted to Percentages</a></li>
  <li><a href="#variables-that-should-be-ok-as-is" id="toc-variables-that-should-be-ok-as-is" class="nav-link" data-scroll-target="#variables-that-should-be-ok-as-is">Variables that should be OK as is</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-task-4.-create-a-factor-for-the-analysis-2-predictor" id="toc-data-task-4.-create-a-factor-for-the-analysis-2-predictor" class="nav-link" data-scroll-target="#data-task-4.-create-a-factor-for-the-analysis-2-predictor">Data Task 4. Create a factor for the Analysis 2 predictor</a></li>
  <li><a href="#data-task-5.-rename-variables-and-save-the-final-chr_2023-tibble" id="toc-data-task-5.-rename-variables-and-save-the-final-chr_2023-tibble" class="nav-link" data-scroll-target="#data-task-5.-rename-variables-and-save-the-final-chr_2023-tibble">Data Task 5. Rename variables and save the final <code>chr_2023</code> tibble</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project A Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>431 Staff </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2023-08-17</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="we-will-post-full-instructions-before-our-first-class.-for-now-ignore-this-draft." class="level1">
<h1>We will post full instructions before our first class. For now, ignore this draft.</h1>
</section>
<section id="what-data-will-i-use" class="level1">
<h1>What Data Will I Use?</h1>
<p>Your Project A will use the 2023 version of the analytic data from <a href="https://www.countyhealthrankings.org/">County Health Rankings</a> (<strong>CHR 2023</strong>). Some prior CHR data has been part of our Labs, but you’ll obtain, clean and manage a new data set for Project A.</p>
<p>The key elements we’ll use are found in the <a href="https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation">Rankings Data &amp; Documentation section</a> at the County Health Rankings website, specifically the National Data &amp; Documentation section site for the 2023 County Health Rankings. Specifically, you’ll need to download three files in order to get and use the data:</p>
<ul>
<li><a href="https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2023_0.csv">the 2023 CHR CSV Analytic Data</a> (a .csv file)</li>
<li><a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2023%20Analytic%20Documentation.pdf">the 2023 CHR CSV/SAS Analytic Data Documentation</a> file (PDF), and</li>
<li><a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2023%20Data%20Dictionary%20%28PDF%29.pdf">the 2023 Data Dictionary</a> (PDF)</li>
</ul>
<p>In addition, when building the Codebook in Data Task 6 below, you’ll use <a href="https://www.countyhealthrankings.org/explore-health-rankings/county-health-rankings-measures">this CHR 2023 Measures link</a> to obtain further details on the variables you select.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In Project A, we will not use data from previous editions of the CHR, and we won’t use the trends data.</p>
</div>
</div>
</section>
<section id="developing-the-data-five-data-tasks" class="level1">
<h1>Developing the Data: Five Data Tasks</h1>
<p>Obtaining and cleaning your data takes a little while, but you can start at any time. First, in broad terms, here are the five data tasks you need to complete in order to build your Project A Proposal.</p>
<ol type="1">
<li>Ingest the raw data from CHR 2023 into a tibble in R called <code>chr_2023_raw</code>, then filter these raw data to only the counties actually ranked by CHR.</li>
<li>In addition to Ohio, select five more states (from the 39 others with at least 20 ranked counties) to study, so that you wind up with at least 300 and no more than 800 counties in your study. Create a new <code>chr_2023</code> tibble that contains only the counties from your chosen six states (including Ohio).</li>
<li>Reduce your data to a selection of nine variables (4 we specify below and 5 more you’ll select from a list we provide), rename them in helpful ways, clean up problems, then save this smaller tibble as <code>chr_2023</code>.</li>
<li>Create a new binary factor (categorical variable) from one of the 5 variables you selected in the previous task, and add it to <code>chr_2023</code> so it now contains 10 variables.</li>
<li>Save the resulting <code>chr_2023</code> tibble as an R data set, and you will share this new <code>.Rds</code> file with us as part of your Proposal.</li>
</ol>
</section>
<section id="data-task-1.-ingest-the-raw-data-into-chr_2023_raw-then-filter-to-ranked-counties" class="level1">
<h1>Data Task 1. Ingest the raw data into <code>chr_2023_raw</code>, then filter to ranked counties</h1>
<p>Begin an R Project just for Project A, and create a Quarto file within that project where you will do your data development work. Working from a template, or from your own best understanding of what works well for you, start by loading the packages you’ll need, including the <code>tidyverse</code> and any other packages you plan to use.</p>
<p>You’ll use <code>read_csv()</code> to ingest your raw <code>.csv</code> file into R and call the resulting tibble <strong>chr_2023_raw</strong>. But as you do this, you’ll need to remove the top row from the .csv within your R code. You should probably look at the raw .csv in Excel or another spreadsheet system so that you know why we need to do this.</p>
<p>To accomplish this, use the <code>skip = 1</code> command within your <code>read_csv()</code>. Sample code follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_url <span class="ot">&lt;-</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2023_0.csv"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>chr_2023_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(data_url, <span class="at">skip =</span> <span class="dv">1</span>, <span class="at">guess_max =</span> <span class="dv">4000</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code should create a <code>chr_2023_raw</code> tibble with 3194 rows (observations) and 720 columns (variables).</p>
<p>To complete Task 1, write code to restrict the <code>chr_2023_raw</code> data to include only the <strong>3082</strong> rows which have “county_ranked” values of 1, since the other rows will not be used by us in this project.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We strongly encourage you to use the <code>filter()</code> function from the <code>dplyr</code> package in the <code>tidyverse</code> to include only the counties ranked by CHR.</p>
</div>
</div>
<p>At the end of Task 1, your <code>chr_2023_raw</code> tibble should have 3082 rows (counties) and 720 columns (variables).</p>
</section>
<section id="data-task-2.-filter-your-data-to-the-300-800-counties-in-six-states-including-ohio" class="level1">
<h1>Data Task 2. Filter your data to the 300-800 counties in six states (including Ohio)</h1>
<p>Now we’ll filter the <code>chr_2023_raw</code> data into a new tibble called <strong>chr_2023</strong> which contains the 300-800 rows (counties) you will actually study in your project.</p>
<p>Your selection must include six states, including:</p>
<ul>
<li>the 88 counties of Ohio, and</li>
<li>all of the counties in <strong>five</strong> additional US states</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>You will write a sentence or two in your Proposal describing the reason for your selections, so you should have one.</p></li>
<li><p>Don’t forget to filter in Task 1 so that only those rows with <code>county_ranked</code> values of 1 are included. Otherwise, your counts won’t match those shown in the table below.</p></li>
<li><p>The table excludes Arizona, Connecticut, Delaware, District of Columbia, Hawaii, Maine, Massachusetts, Nevada, New Hampshire, Rhode Island and Vermont because they have fewer than 20 ranked counties.</p></li>
</ol>
</div>
</div>
<section id="states-you-can-select" class="level2">
<h2 class="anchored" data-anchor-id="states-you-can-select">States You Can Select</h2>
<p>The number of counties (with <code>county_ranked</code> values of 1) in each state (specified using its two-digit FIPS code and two-letter postal abbreviation) is listed below, for your convenience.</p>
<table class="table">
<colgroup>
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><code>statecode</code></th>
<th style="text-align: right;"><code>state</code></th>
<th style="text-align: right;">ranked <br> counties</th>
<th>State <br> Name</th>
<th style="text-align: right;"><code>statecode</code></th>
<th style="text-align: right;"><code>state</code></th>
<th style="text-align: right;">ranked <br> counties</th>
<th>State <br> Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>01</code></td>
<td style="text-align: right;">AL</td>
<td style="text-align: right;">67</td>
<td>Alabama</td>
<td style="text-align: right;"><code>31</code></td>
<td style="text-align: right;">NE</td>
<td style="text-align: right;">79</td>
<td>Nebraska</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>02</code></td>
<td style="text-align: right;">AK</td>
<td style="text-align: right;">24</td>
<td>Alaska</td>
<td style="text-align: right;"><code>34</code></td>
<td style="text-align: right;">NJ</td>
<td style="text-align: right;">21</td>
<td>New Jersey</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>05</code></td>
<td style="text-align: right;">AR</td>
<td style="text-align: right;">75</td>
<td>Arkansas</td>
<td style="text-align: right;"><code>35</code></td>
<td style="text-align: right;">NM</td>
<td style="text-align: right;">32</td>
<td>New Mexico</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>06</code></td>
<td style="text-align: right;">CA</td>
<td style="text-align: right;">58</td>
<td>California</td>
<td style="text-align: right;"><code>36</code></td>
<td style="text-align: right;">NY</td>
<td style="text-align: right;">62</td>
<td>New York</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>08</code></td>
<td style="text-align: right;">CO</td>
<td style="text-align: right;">59</td>
<td>Colorado</td>
<td style="text-align: right;"><code>37</code></td>
<td style="text-align: right;">NC</td>
<td style="text-align: right;">100</td>
<td>North Carolina</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>12</code></td>
<td style="text-align: right;">FL</td>
<td style="text-align: right;">67</td>
<td>Florida</td>
<td style="text-align: right;"><code>38</code></td>
<td style="text-align: right;">ND</td>
<td style="text-align: right;">48</td>
<td>North Dakota</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>13</code></td>
<td style="text-align: right;">GA</td>
<td style="text-align: right;">159</td>
<td>Georgia</td>
<td style="text-align: right;"><code>39</code></td>
<td style="text-align: right;"><strong>OH</strong></td>
<td style="text-align: right;"><strong>88</strong></td>
<td><strong>Ohio</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>16</code></td>
<td style="text-align: right;">ID</td>
<td style="text-align: right;">43</td>
<td>Idaho</td>
<td style="text-align: right;"><code>40</code></td>
<td style="text-align: right;">OK</td>
<td style="text-align: right;">77</td>
<td>Oklahoma</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>17</code></td>
<td style="text-align: right;">IL</td>
<td style="text-align: right;">102</td>
<td>Illinois</td>
<td style="text-align: right;"><code>41</code></td>
<td style="text-align: right;">OR</td>
<td style="text-align: right;">35</td>
<td>Oregon</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>18</code></td>
<td style="text-align: right;">IN</td>
<td style="text-align: right;">92</td>
<td>Indiana</td>
<td style="text-align: right;"><code>42</code></td>
<td style="text-align: right;">PA</td>
<td style="text-align: right;">67</td>
<td>Pennsylvania</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>19</code></td>
<td style="text-align: right;">IA</td>
<td style="text-align: right;">99</td>
<td>Iowa</td>
<td style="text-align: right;"><code>45</code></td>
<td style="text-align: right;">SC</td>
<td style="text-align: right;">46</td>
<td>South Carolina</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>20</code></td>
<td style="text-align: right;">KS</td>
<td style="text-align: right;">104</td>
<td>Kansas</td>
<td style="text-align: right;"><code>46</code></td>
<td style="text-align: right;">SD</td>
<td style="text-align: right;">61</td>
<td>South Dakota</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>21</code></td>
<td style="text-align: right;">KY</td>
<td style="text-align: right;">120</td>
<td>Kentucky</td>
<td style="text-align: right;"><code>47</code></td>
<td style="text-align: right;">TN</td>
<td style="text-align: right;">95</td>
<td>Tennessee</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>22</code></td>
<td style="text-align: right;">LA</td>
<td style="text-align: right;">64</td>
<td>Louisiana</td>
<td style="text-align: right;"><code>48</code></td>
<td style="text-align: right;">TX</td>
<td style="text-align: right;">244</td>
<td>Texas</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>24</code></td>
<td style="text-align: right;">MD</td>
<td style="text-align: right;">24</td>
<td>Maryland</td>
<td style="text-align: right;"><code>49</code></td>
<td style="text-align: right;">UT</td>
<td style="text-align: right;">28</td>
<td>Utah</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>26</code></td>
<td style="text-align: right;">MI</td>
<td style="text-align: right;">83</td>
<td>Michigan</td>
<td style="text-align: right;"><code>51</code></td>
<td style="text-align: right;">VA</td>
<td style="text-align: right;">133</td>
<td>Virginia</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>27</code></td>
<td style="text-align: right;">MN</td>
<td style="text-align: right;">87</td>
<td>Minnesota</td>
<td style="text-align: right;"><code>53</code></td>
<td style="text-align: right;">WA</td>
<td style="text-align: right;">39</td>
<td>Washington</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>28</code></td>
<td style="text-align: right;">MS</td>
<td style="text-align: right;">82</td>
<td>Mississippi</td>
<td style="text-align: right;"><code>54</code></td>
<td style="text-align: right;">WV</td>
<td style="text-align: right;">55</td>
<td>West Virginia</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>29</code></td>
<td style="text-align: right;">MO</td>
<td style="text-align: right;">115</td>
<td>Missouri</td>
<td style="text-align: right;"><code>55</code></td>
<td style="text-align: right;">WI</td>
<td style="text-align: right;">72</td>
<td>Wisconsin</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>30</code></td>
<td style="text-align: right;">MT</td>
<td style="text-align: right;">47</td>
<td>Montana</td>
<td style="text-align: right;"><code>56</code></td>
<td style="text-align: right;">WY</td>
<td style="text-align: right;">23</td>
<td>Wyoming</td>
</tr>
</tbody>
</table>
<p>Select six states (including <code>OH</code>) yielding a total of 300-800 counties.</p>
<ul>
<li>For example, one possible combination would be <code>ID</code> (43), <code>OR</code> (35), <code>MT</code> (47), <code>ND</code> (48) and <code>WA</code> (39) with <code>OH</code> (88) yielding exactly 300 counties.</li>
<li>another possibility would be <code>GA</code> (159), <code>TX</code> (244), <code>IL</code> (102), <code>MN</code> (87) and <code>KY</code> (120) with <code>OH</code> (88) yielding exactly 800 counties.</li>
</ul>
<p>After making your selection, and filtering the data, you should have a tibble called <code>chr_2023</code> which contains all of the 300-800 counties in your six states, and 720 columns.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>After reducing your tibble to your selected six states, it is very important to then <strong>convert</strong> the <code>state</code> variable to a <code>factor</code> in R.</p>
</div>
</div>
</section>
</section>
<section id="data-task-3.-add-five-selected-measures-to-four-required-variables-and-clean-up-chr_2023" class="level1">
<h1>Data Task 3. Add five selected measures to four required variables and clean up <code>chr_2023</code></h1>
<p>Next, you will identify variables from the your existing <code>chr_2023</code> tibble describing your selected sample of counties.</p>
<p>In particular, you will select exactly nine variables (columns) from the 720 you should have at the start of Task 3. These nine variables must include the following four:</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 83%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variable <br> Name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>fipscode</code></td>
<td>the five-digit FIPS code for the county, which will be a convenient ID variable that is distinct for each row in your tibble</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>county</code></td>
<td>the name of the county, which will be useful for labeling and identifying the counties</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>state</code></td>
<td>a multi-categorical (with 6 levels) variable of two-letter postal abbreviations for your six selected states (this should be a factor variable thanks to your making it one at the end of Task 2)</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>county_ranked</code></td>
<td>tells us whether the row should be included in our data <br> (all rows should have <code>county_ranked == 1</code>)</td>
</tr>
</tbody>
</table>
<p>This set of four variables will then be followed by five variables that you will select from among the 45 listed below.</p>
<ul>
<li>Each of these must be of the form <code>vXXX_rawvalue</code> (note: to select the entire group of raw value variables, you might try <code>select(ends_with("rawvalue"))</code> as part of a pipe.)</li>
<li>There are many <code>vXXX_rawvalue</code> variables in the CHR data which we don’t include in the list below, usually because of substantial missing data.</li>
</ul>
<section id="select-five-of-these-45-variables" class="level2">
<h2 class="anchored" data-anchor-id="select-five-of-these-45-variables">Select five of these 45 variables</h2>
<p>As part of the selection process, you should be developing appropriate <strong>research questions</strong> that lead to the identification of smart measures of interest (from those available) for predictors and outcomes in our two Analyses.</p>
<p>You must select your five variables from the 45 variables listed below. We show them here in the order in which they appear in the raw file. The listing “v001” in this table actually refers to the variable named “<strong>v001_rawvalue</strong>”.</p>
<pre><code> [1] "v001" "v002" "v036" "v042" "v037" "v009" "v011" "v133" "v070" "v132"
[11] "v049" "v134" "v045" "v085" "v004" "v088" "v005" "v050" "v155" "v168"
[21] "v023" "v044" "v140" "v135" "v125" "v136" "v067" "v147" "v127" "v060"
[31] "v139" "v083" "v143" "v169" "v151" "v063" "v177" "v156" "v154" "v166" 
[41] "v053" "v126" "v059" "v057" "v058"</code></pre>
<p>For example, <code>v001_rawvalue</code> shows the raw values for the premature death measure. If you select this variable, it is up to you to use the documentation in the two PDF files I have linked to, as well as the information on the County Health Rankings website, to get a reasonable understanding of what the variable measures, and how it was collected.</p>
</section>
<section id="what-will-these-variables-become" class="level2">
<h2 class="anchored" data-anchor-id="what-will-these-variables-become">What will these variables become?</h2>
<p>Each of the five variables you select should be of some interest to you on its own, in terms of either providing a health outcome of interest, or potentially providing useful information about a feature of the county that might relate to that health outcome. Be sure to read this entire Data page before selecting your variables, so you are aware of some features of the data we disclose below.</p>
<ul>
<li>Variable 1 will be your outcome for Analysis 1. It should be a measure describing some aspect of a community’s health<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, rather than a demographic characteristic.</li>
<li>Variable 2 will be your predictor for Analysis 1, so the relationship between variables 1 and 2 should be of interest to you.</li>
<li>Variable 3 will be your outcome for Analysis 2. Like variable 1, it should describe some aspect of a community’s health, rather than just its demographics.</li>
<li>Variable 4 (after you categorize it, later) will be your predictor for Analysis 2. Again, the relationship between variables 3 and 4 should be of interest.</li>
<li>Variable 5 is an alternate choice, appropriate to serve as a replacement for any of the other four variables in your analytic work.</li>
</ul>
</section>
<section id="information-to-help-select-and-build-a-codebook" class="level2">
<h2 class="anchored" data-anchor-id="information-to-help-select-and-build-a-codebook">Information to help select and build a codebook</h2>
<p>The <a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2023%20Analytic%20Documentation.pdf">2023 CHR Analytic Data Documentation</a> file (PDF), and the <a href="https://www.countyhealthrankings.org/sites/default/files/media/document/DataDictionary_2023.pdf">2023 Data Dictionary</a> file (also PDF) are crucial here, as those are the ones that explain what the available variables mean, and how they should be labeled. In building your codebook, you will also need look up each measure you select at <a href="https://www.countyhealthrankings.org/2023-measures">this CHR 2023 Measures link</a>.</p>
</section>
<section id="how-to-clean-your-selected-variables" class="level2">
<h2 class="anchored" data-anchor-id="how-to-clean-your-selected-variables">How To Clean Your Selected Variables</h2>
<p>Find each of your five selected variables on one of the lists below, then do what is suggested below as part of your data development work, rename the variable appropriately, and use that version in your codebook.</p>
<ul>
<li>If you plan to use the variable as your categorical predictor, you should still make the appropriate change to the original quantitative version as indicated below.</li>
</ul>
<p>The descriptions provided in these instructions associated with each variable are available as the first (deleted in R) row in the .csv file, and are also specified in the <a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2023%20Analytic%20Documentation.pdf">2023 CHR Analytic Data Documentation</a> PDF file.</p>
<section id="ratios-that-need-converting" class="level3">
<h3 class="anchored" data-anchor-id="ratios-that-need-converting">Ratios That Need Converting</h3>
<p>These two variables are specified as providers per population in the raw data file. You will want to take the reciprocal (1/raw value) to rescale the results in terms of population per provider, which should ease interpretation.</p>
<ul>
<li>Note that after rescaling by taking the reciprocal, you may see some counties with infinite ratios, which should then be changed to <strong>missing</strong> values.</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v004</td>
<td style="text-align: left;">Primary care physicians</td>
<td style="text-align: right;">v088</td>
<td style="text-align: left;">Dentists</td>
</tr>
</tbody>
</table>
</section>
<section id="variables-that-should-be-rescaled" class="level3">
<h3 class="anchored" data-anchor-id="variables-that-should-be-rescaled">Variables that should be rescaled</h3>
<p>Two of the variables you might choose should be rescaled by division so as to more closely match the scales of other variables you’ll study.</p>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 37%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
<th style="text-align: left;">What to do?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v001</td>
<td style="text-align: left;">Premature death</td>
<td style="text-align: left;">Divide by 100 to represent losses per 1000 population</td>
</tr>
<tr class="even">
<td style="text-align: right;">v063</td>
<td style="text-align: left;">Median household income</td>
<td style="text-align: left;">Divide by 1000 to represent income in thousands of dollars</td>
</tr>
</tbody>
</table>
<ul>
<li>The variable <code>v001</code> is very tempting to use an outcome. That’s OK, but be sure to consider the use of either <code>v127</code> or <code>v147</code> as well as an outcome if mortality interests you. Do not use <code>v001</code>, <code>v127</code> and <code>v147</code> in the same Analysis.</li>
</ul>
</section>
<section id="variables-that-are-proportions-should-be-converted-to-percentages" class="level3">
<h3 class="anchored" data-anchor-id="variables-that-are-proportions-should-be-converted-to-percentages">Variables that are Proportions should be converted to Percentages</h3>
<p>Each of the variables listed below are proportions (between 0 and 1). Before you use them in any analyses, <strong>multiply them by 100</strong> in your data development (using the <code>mutate</code> function) to turn their values into percentages (between 0 and 100.) We’re doing this to ease your interpretation of these variables.</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 42%">
<col style="width: 7%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v002</td>
<td style="text-align: left;">Poor or fair health</td>
<td style="text-align: right;">v083</td>
<td style="text-align: left;">Limited access to healthy foods</td>
</tr>
<tr class="even">
<td style="text-align: right;">v009</td>
<td style="text-align: left;">Adult smoking</td>
<td style="text-align: right;">v085</td>
<td style="text-align: left;">Uninsured</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v011</td>
<td style="text-align: left;">Adult obesity</td>
<td style="text-align: right;">v126</td>
<td style="text-align: left;">Proportion Non-Hispanic White (see note below)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v023</td>
<td style="text-align: left;">Unemployment</td>
<td style="text-align: right;">v132</td>
<td style="text-align: left;">Access to exercise opportunities</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v037</td>
<td style="text-align: left;">Low birthweight</td>
<td style="text-align: right;">v134</td>
<td style="text-align: left;">Proportion of driving deaths with alcohol involvement</td>
</tr>
<tr class="even">
<td style="text-align: right;">v049</td>
<td style="text-align: left;">Excessive drinking</td>
<td style="text-align: right;">v136</td>
<td style="text-align: left;">Severe housing problems</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v050</td>
<td style="text-align: left;">Mammography screening</td>
<td style="text-align: right;">v139</td>
<td style="text-align: left;">Food insecurity</td>
</tr>
<tr class="even">
<td style="text-align: right;">v053</td>
<td style="text-align: left;">Proportion ages 65 and older</td>
<td style="text-align: right;">v143</td>
<td style="text-align: left;">Insufficient sleep</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v057</td>
<td style="text-align: left;">Proportion Female</td>
<td style="text-align: right;">v154</td>
<td style="text-align: left;">Severe housing cost burden</td>
</tr>
<tr class="even">
<td style="text-align: right;">v058</td>
<td style="text-align: left;">Proportion Rural</td>
<td style="text-align: right;">v155</td>
<td style="text-align: left;">Flu vaccinations</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v059</td>
<td style="text-align: left;">Proportion not proficient in English</td>
<td style="text-align: right;">v166</td>
<td style="text-align: left;">Broadband access</td>
</tr>
<tr class="even">
<td style="text-align: right;">v060</td>
<td style="text-align: left;">Diabetes prevalence</td>
<td style="text-align: right;">v168</td>
<td style="text-align: left;">High school completion</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v067</td>
<td style="text-align: left;">Driving alone to work</td>
<td style="text-align: right;">v177</td>
<td style="text-align: left;">Voter turnout</td>
</tr>
<tr class="even">
<td style="text-align: right;">v070</td>
<td style="text-align: left;">Physical inactivity</td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<ul>
<li>Regarding variable <code>v126</code>: A serious look at the impact of race/ethnicity is beyond the scope of Project A. If you are interested in studying race and ethnicity and their impact on a health outcome, we suggest using <code>v126</code> to incorporate this dimension as a predictor (or its inverse, 1 - <code>v126</code>), rather than including any other race/ethnicity variables. This is because there’s more variation in the <code>v126</code> data across the reported counties.</li>
</ul>
</section>
<section id="variables-that-should-be-ok-as-is" class="level3">
<h3 class="anchored" data-anchor-id="variables-that-should-be-ok-as-is">Variables that should be OK as is</h3>
<p>The variables listed below should be useful as they are. Most of them are ratios, although a few are averages or indexes. The main issue for these variables is correctly specifying the units of measurement (note that the indexes don’t have units.)</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 42%">
<col style="width: 7%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v005</td>
<td style="text-align: left;">Preventable hospital stays</td>
<td style="text-align: right;">v133</td>
<td style="text-align: left;">Food environment index</td>
</tr>
<tr class="even">
<td style="text-align: right;">v036</td>
<td style="text-align: left;">Poor physical health days</td>
<td style="text-align: right;">v135</td>
<td style="text-align: left;">Injury deaths</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v042</td>
<td style="text-align: left;">Poor mental health days</td>
<td style="text-align: right;">v140</td>
<td style="text-align: left;">Social associations</td>
</tr>
<tr class="even">
<td style="text-align: right;">v044</td>
<td style="text-align: left;">Income inequality</td>
<td style="text-align: right;">v147</td>
<td style="text-align: left;">Life expectancy</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v045</td>
<td style="text-align: left;">Sexually transmitted infections</td>
<td style="text-align: right;">v151</td>
<td style="text-align: left;">Gender pay gap</td>
</tr>
<tr class="even">
<td style="text-align: right;">v125</td>
<td style="text-align: left;">Air pollution - particulate matter</td>
<td style="text-align: right;">v156</td>
<td style="text-align: left;">Traffic volume</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v127</td>
<td style="text-align: left;">Premature age-adjusted mortality</td>
<td style="text-align: right;">v169</td>
<td style="text-align: left;">School funding adequacy (gap measured in dollars per pupil)</td>
</tr>
</tbody>
</table>
<ul>
<li>If you are considering <code>v127</code> or <code>v147</code>, please read my note about variable <code>v001</code> under the “Variables that should be rescaled” table earlier.</li>
</ul>
</section>
</section>
</section>
<section id="data-task-4.-create-a-factor-for-the-analysis-2-predictor" class="level1">
<h1>Data Task 4. Create a factor for the Analysis 2 predictor</h1>
<p>Create a new categorical variables (factor) based on your fourth variable, and add this new factor to your <strong>chr_2023</strong> tibble. You’ll also retain the original (quantitative) version of this variable, so your tibble will now have 10 variables.</p>
<ol type="1">
<li>Divide the values in your variable 4 into three groups, as follows:
<ul>
<li>values in the lowest 40% of your sample’s observations (the low group)</li>
<li>values in the middle 20% of your sample’s observations (the middle group)</li>
<li>values in the highest 40% of your sample’s observations (the high group)</li>
</ul></li>
<li>Create a new factor which has two levels, low and high (although you can use other labels if you prefer), based on your three-level categorization, and treats the rest (middle group) as missing.
<ul>
<li>This should yield (from your original set of 300-800 counties) between 120 and 320 counties having the low level, 120-320 having the high level, and 60-160 missing values in the new factor variable.</li>
</ul></li>
<li>Add the resulting (binary) factor to your <strong>chr_2023</strong> tibble.</li>
</ol>
</section>
<section id="data-task-5.-rename-variables-and-save-the-final-chr_2023-tibble" class="level1">
<h1>Data Task 5. Rename variables and save the final <code>chr_2023</code> tibble</h1>
<p>Revise the <strong>chr_2023</strong> tibble to arrange the variables in the following order:</p>
<ol type="1">
<li><code>fipscode</code>,</li>
<li><code>state</code>,</li>
<li><code>county</code>,</li>
<li>your selected (and renamed) variable 1 (Analysis 1 outcome),</li>
<li>your selected (and renamed) variable 2 (Analysis 1 predictor),</li>
<li>your selected (and renamed) variable 3 (Analysis 2 outcome),</li>
<li>your binary factor describing variable 4 (Analysis 2 predictor),</li>
<li>your original (quantitative version) of variable 4,</li>
<li>your selected (and renamed) variable 5 (extra variable), and</li>
<li>the <code>county_ranked</code> variable (whose values must all be 1)</li>
</ol>
<p>All of your selected variables should be <strong>renamed</strong> (and also have <code>clean_names()</code> from the <code>janitor</code> package applied) so as to have descriptive and maximally helpful variable names.</p>
<ul>
<li>For example, if you have decided to use as a quantitative variable something like <code>v009_rawvalue</code>, which is about adult smoking, you should rename the variable <code>v009_rawvalue</code> to <strong>adult_smoking</strong> in your tibble.</li>
<li>If <code>v009_rawvalue</code> (about adult smoking) is to be your categorical factor, then you should include both the original quantitative value (renamed <code>adult_smoking_raw</code>) and your categorical variable that you’ll actually use in analyses, which should be named <code>adult_smoking_cat</code>.</li>
</ul>
<p>Save this final <strong>chr_2023</strong> tibble as an R data set (.Rds file) in your R Project, with the file name <strong>chr_2023_YOURNAME.Rds</strong>. You will share this file with us as part of your proposal. If you like, you can store this <code>.Rds</code> file in a <code>data</code> subdirectory within your R Project.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>After your cleaning is done, each row in your <code>chr_2023</code> tibble should contain all of the counties within the 6 states you are studying, and no other counties should be included in your tibble.</li>
<li>If data for some counties are missing in the raw data for one or more of your variables (and this will be true at least for your binary factor representing low and high levels of variable 4), then these data should be indicated as missing (using NA) in the tibble.</li>
<li>There is no need to set a seed in this process, as you are not doing anything that involves selecting a random sample.</li>
</ol>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Many of the variables, but probably <em>not</em> all 45 of them, meet this requirement. It’s up to you to make good choices.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>